//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMGym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classes
    {
        public int class_id { get; set; }
        public string name { get; set; }
        public int duration_minutes { get; set; }
        public string difficulty { get; set; }
        public string status { get; set; }
        public int branch_id { get; set; }
        public int trainer_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int room_id { get; set; }
    
        public virtual Branches Branches { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual Trainers Trainers { get; set; }
    }
}
