//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMGym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int equipment_id { get; set; }
        public int branch_id { get; set; }
        public string name { get; set; }
        public string model { get; set; }
        public string serialNumber { get; set; }
        public System.DateTime purchaseDate { get; set; }
    
        public virtual Branches Branches { get; set; }
    }
}
