//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMGym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int invoice_id { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public int branch_id { get; set; }
        public decimal amount { get; set; }
        public int paymentStatus_id { get; set; }
    
        public virtual Branches Branches { get; set; }
        public virtual Members Members { get; set; }
        public virtual PaymentStatuses PaymentStatuses { get; set; }
        public virtual Vendors Vendors { get; set; }
    }
}
