//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMGym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int invoice_id { get; set; }
        public int vendor_id { get; set; }
        public int branch_id { get; set; }
        public decimal total_amount { get; set; }
        public int payment_status_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual Branches Branches { get; set; }
        public virtual PaymentStatuses PaymentStatuses { get; set; }
        public virtual Vendors Vendors { get; set; }
    }
}
