//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMGym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotions
    {
        public int promo_id { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public decimal discountPercentageAmount { get; set; }
    }
}
