//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMGym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainers
    {
        public int trainer_id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public System.DateTime hireDate { get; set; }
        public int branch_id { get; set; }
    
        public virtual Branches Branches { get; set; }
    }
}
